baseURL = 'https://trend-surf.com'
languageCode = 'ja-jp'
title = 'TrendSurf'
theme = 'introduction'

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showMenu                     = true                    # Show navigation menu
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page 
    dateFormat                   = "2006, 1/2"
    email                        = "support@trend-surf.com"   # E-mail address for contact section

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        timeZone                 = "Tokyo/Japan"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "ja-JP"                 # Language specific format to use

    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[[menu.main]]
     name    = "Home"
     url     = "/"
     weight  = 1
[[menu.main]]
     name    = "About"
     url     = "/#about"
     weight  = 2
[[menu.main]]
     name    = "Works"
     url     = "/#works"
     weight  = 3
[[menu.main]]
     name    = "Privacy Policy"
     url     = "/privacy-policy/"
     weight  = 4
[[menu.main]]
     name    = "Contact"
     url     = "/#contact"
     weight  = 5

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[footer_text]
    other = "hoge"
